In [ ]:
1번 답

In [12]:
import pandas as pd
#code를 바로 변경하여 답안을 완성 해 주세요.
def ageDif(x):
    if x<=36:
        return "Y"
    else:
        return "N"

excelDF = pd.read_csv('data/employee_list.csv')
excelDF['판별']=''
excelDF.판별= excelDF.age.apply(ageDif)
excelDF

      name  age department   tel 판별
0   SeeJin   25         IT  4040  Y
1  JeeHyun   30        R&D  2278  Y
2     InKi   30         QA  4350  Y
3    JunHo   40         HR  4466  N
4    MinSu   45       TEST  3476  N
5   Chanho   25        PCS  2525  Y

In [5]:
import pandas as pd
df = pd.read_excel('C://Users//suhna//Desktop//IM_TEST_DF1.xlsx')
df

  NAME TITLE   JOB  SALARY
0  나서니    노비   개발자  100000
1  박성하    도비   RUN  200000
2  홍인기    사원  앰코스타  240000
3  김지현  우수사원   노동자  250000

2번 답

In [10]:
df = pd.read_excel('C:\jupyter_notebook_Source\python_intermediate\im_test_문서\IM_TEST_DF1.xlsx')
df.loc[df['SALARY']>=200000,:]
df.loc[df['TITLE'].str.contains('사원')]

  NAME TITLE   JOB  SALARY
2  홍인기    사원  앰코스타  240000
3  김지현  우수사원   노동자  250000

3번 답

In [11]:
temp = pd.read_excel('C:\jupyter_notebook_Source\python_intermediate\im_test_문서\IM_TEST_DF1.xlsx')
temp2 = pd.read_excel('C:\jupyter_notebook_Source\python_intermediate\im_test_문서\IM_TEST_DF2.xlsx')
sumdf = pd.concat([temp,temp2])
sumdf = sumdf.dropna(how='any')
sumdf = sumdf[sumdf['SALARY']<=240000]
sumdf = sumdf.drop_duplicates(['NAME'], keep = 'first')
result = sumdf[['NAME','TITLE']]
result

  NAME TITLE
0  나서니    노비
1  박성하    도비
2  홍인기    사원
1  윤성하    도비

In [ ]:
4번답

In [4]:
# 네이버 
import requests # 사이트의 webpage 문서를 back ground 에서 down할 수 있도록
from bs4 import BeautifulSoup
ent = input("기업을 입력 해 주세요-->")
url = "https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=" + ent + " 주가"
html = requests.get(url).text
soup = BeautifulSoup(html, 'html.parser')
tempTxt = soup.find('span', 
        class_='spt_con up').text
if tempTxt =='':
    soup.find('span', 
        class_='spt_con eq').text
t = tempTxt.split(' ')
print(f"현재 {ent} 주가는 {t[2]} 입니다.")

기업을 입력 해 주세요-->하이닉스
현재 하이닉스 주가는 100,500 입니다.

In [ ]:
5번답

In [7]:
#find_elements_by_xpath
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By

driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get("https://www.melon.com/chart/")

title_list = driver.find_elements(By.XPATH,"//div[contains(@class,'ellipsis rank01')]")
singer_list = driver.find_elements(By.XPATH,"//div[contains(@class,'ellipsis rank02')]")
for i in range(0, len(title_list)):
    print("가수:"+singer_list[i].text+", 제목 :"+title_list[i].text)
driver.quit()

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 103.0.5060
[WDM] - Get LATEST chromedriver version for 103.0.5060 google-chrome
[WDM] - Driver [C:\Users\suhna\.wdm\drivers\chromedriver\win32\103.0.5060.134\chromedriver.exe] found in cache
C:\Users\suhna\AppData\Local\Temp\9\ipykernel_24112\3952849706.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())

가수:WSG워너비 (가야G), 제목 :그때 그 순간 그대로 (그그그)
가수:WSG워너비 (4FIRE), 제목 :보고싶었어
가수:IVE (아이브), 제목 :LOVE DIVE
가수:나연 (TWICE), 제목 :POP!
가수:싸이 (PSY), 제목 :That That (prod. & feat. SUGA of BTS)
가수:BIG Naughty (서동현), 제목 :정이라고 하자 (Feat. 10CM)
가수:(여자)아이들, 제목 :TOMBOY
가수:경서, 제목 :나의 X에게
가수:멜로망스, 제목 :사랑인가 봐
가수:임영웅, 제목 :사랑은 늘 도망가
가수:aespa, 제목 :Girls
가수:임영웅, 제목 :우리들의 블루스
가수:10CM, 제목 :그라데이션
가수:WSG워너비 (오아시소), 제목 :Clink Clink (클링 클링)
가수:임영웅, 제목 :다시 만날 수 있을까
가수:볼빨간사춘기, 제목 :Love story
가수:BE'O (비오), 제목 :LOVE me
가수:BIGBANG (빅뱅), 제목 :봄여름가을겨울 (Still Life)
가수:LE SSERAFIM (르세라핌), 제목 :FEARLESS
가수:주호, 제목 :내가 아니라도
가수:임영웅, 제목 :무지개
가수:ITZY (있지), 제목 :SNEAKERS
가수:김민석 (멜로망스), 제목 :취중고백
가수:임영웅, 제목 :이제 나만 믿어요
가수:선미, 제목 :열이올라요 (Heart Burn)
가수:임영웅, 제목 :아버지
가수:세븐틴, 제목 :HOT
가수:aespa, 제목 :도깨비불 (Illusion)
가수:세븐틴, 제목 :_WORLD
가수:Red Velvet (레드벨벳), 제목 :Feel My Rhythm
가수:임영웅, 제목 :손이 참 곱던 그대
가수:이무진, 제목 :신호등
가수:임영웅, 제목 :A bientot
가수:IVE (아이브), 제목 :ELEVEN
가수:방탄소년단, 제목 :Yet To Come
가수:임영웅, 제목 :사랑해 진짜
가수:Charlie Puth, 정국, 방탄소년단, 제목 :Left and Right (Feat. Jung Kook of BTS)
가수:경서예지, 전건호, 제목 :다정히 내 이름을 부르면
가수:임영웅, 제목 :인생찬가
가수:주시크 (Joosiq), 제목 :아무래도 난
가수:이석훈, 제목 :바보에게 바보가 (웹툰 '연애의 발견' X 이석훈)
가수:임영웅, 제목 :연애편지
가수:방탄소년단, 제목 :Dynamite
가수:임영웅, 제목 :사랑역
가수:박재범, 제목 :GANADARA (Feat. 아이유)
가수:임영웅, 제목 :보금자리
가수:The Kid LAROI, Justin Bieber, 제목 :STAY
가수:임영웅, 제목 :사랑해요 그대를
가수:(여자)아이들, 제목 :MY BAG
가수:WINNER, 제목 :I LOVE U
가수:방탄소년단, 제목 :Butter
가수:케이시 (Kassy), 제목 :늦은 밤 헤어지긴 너무 아쉬워
가수:태연 (TAEYEON), 제목 :INVU
가수:Charlie Puth, 제목 :That's Hilarious
가수:MSG워너비(M.O.M), 제목 :듣고 싶을까
가수:aespa, 제목 :Next Level
가수:성시경, 제목 :너의 모든 순간
가수:방탄소년단, 제목 :Permission to Dance
가수:#안녕, 제목 :해요 (2022)
가수:태연 (TAEYEON), 제목 :Weekend
가수:다비치, 제목 :팡파레
가수:주시크 (Joosiq), 제목 :너를 생각해
가수:세븐틴, 제목 :Darl+ing
가수:YENA (최예나), 제목 :SMILEY (Feat. BIBI)
가수:방탄소년단, 제목 :봄날
가수:임재현, 제목 :고백하는 취한밤에 (Prod. 2soo)
가수:sokodomo, 제목 :회전목마 (Feat. Zion.T, 원슈타인) (Prod. Slom)
가수:아이유, 제목 :드라마
가수:MSG워너비(M.O.M), 제목 :바라만 본다
가수:케이시 (Kassy), 제목 :언제나 사랑해
가수:Coldplay, 방탄소년단, 제목 :My Universe
가수:아이유, 제목 :내 손을 잡아
가수:BE'O (비오), 제목 :리무진 (Feat. MINO) (Prod. GRAY)
가수:청하, 제목 :Sparkling
가수:경서, 제목 :밤하늘의 별을(2020)
가수:세븐틴, 제목 :CHEERS
가수:디핵 (D-Hack), PATEKO (파테코), 제목 :OHAYO MY NIGHT
가수:제시 (Jessi), 제목 :ZOOM
가수:폴킴, 제목 :모든 날, 모든 순간 (Every day, Every Moment)
가수:케이시 (Kassy), 제목 :사랑이야
가수:지민, 하성운, 제목 :With you
가수:세븐틴, 제목 :돌고 돌아
가수:아이유, 제목 :Celebrity
가수:Justin Bieber, 제목 :Off My Face
가수:아이유, 제목 :strawberry moon
가수:BIG Naughty (서동현), 제목 :낭만교향곡 (Feat. CHANGMO, 박재범)
가수:세븐틴, 제목 :Fallin' Flower (Korean Ver.)
가수:자우림, 제목 :스물다섯, 스물하나
가수:aespa, 제목 :Savage
가수:브레이브걸스, 제목 :롤린 (Rollin')
가수:STAYC(스테이씨), 제목 :BEAUTIFUL MONSTER
가수:V.O.S, 제목 :미친 것처럼
가수:아이유, 제목 :라일락
가수:주호, 제목 :그 하루(feat.반하나)
가수:BE'O (비오), 제목 :문득
가수:헤이즈 (Heize), 제목 :없었던 일로
가수:이무진, 제목 :눈이 오잖아(Feat.헤이즈)
가수:aespa, 제목 :Life′s Too Short (English Ver.)
가수:호미들, 제목 :사이렌 Remix (Feat. UNEDUCATED KID, Paul Blanco)
가수:아이유, 제목 :Blueming

In [ ]:
6번 답안

In [57]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get("https://www.melon.com/chart/")

title_list = driver.find_elements_by_xpath("//div[contains(@class,'ellipsis rank01')]")
singer_list = driver.find_elements_by_xpath("//div[contains(@class,'ellipsis rank02')]")
titleList=list()
nameList=list()
for i in range(0, len(title_list)):
    #print("가수:"+singer_list[i].text+", 제목 :"+title_list[i].text)
    titleList.append(title_list[i].text)
    nameList.append(singer_list[i].text)
driver.quit()
data = {
        '제목': titleList,
        '가수': nameList
        }
df = pd.DataFrame(data,columns=['제목','가수'])
df

====== WebDriver manager ======
Current google-chrome version is 102.0.5005
Get LATEST chromedriver version for 102.0.5005 google-chrome
Driver [C:\Users\suhna\.wdm\drivers\chromedriver\win32\102.0.5005.61\chromedriver.exe] found in cache
C:\Users\suhna\AppData\Local\Temp\4/ipykernel_10432/2340434689.py:4: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())
C:\Users\suhna\AppData\Local\Temp\4/ipykernel_10432/2340434689.py:7: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  title_list = driver.find_elements_by_xpath("//div[contains(@class,'ellipsis rank01')]")
C:\Users\suhna\AppData\Local\Temp\4/ipykernel_10432/2340434689.py:8: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  singer_list = driver.find_elements_by_xpath("//div[contains(@class,'ellipsis rank02')]")

                                                제목                 가수
0            That That (prod. & feat. SUGA of BTS)           싸이 (PSY)
1                                           TOMBOY            (여자)아이들
2                                        LOVE DIVE          IVE (아이브)
3                             봄여름가을겨울 (Still Life)       BIGBANG (빅뱅)
4                                           사랑인가 봐               멜로망스
..                                             ...                ...
95  만남은 쉽고 이별은 어려워 (Feat. Leellamarz) (Prod. TOIL)       베이식 (Basick)
96                                             노래해                세븐틴
97                                            어제처럼                 폴킴
98                                       Real Love  오마이걸 (OH MY GIRL)
99                                 IF you leave me                세븐틴

[100 rows x 2 columns]

In [ ]:
7번 정답

In [96]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import win32com.client

driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get("https://www.melon.com/chart/")

title_list = driver.find_elements_by_xpath("//div[contains(@class,'ellipsis rank01')]")
singer_list = driver.find_elements_by_xpath("//div[contains(@class,'ellipsis rank02')]")
titleList=list()
nameList=list()
rank=list()
cnt=0
for i in range(0, len(title_list)):
    cnt=cnt+1
    #print("가수:"+singer_list[i].text+", 제목 :"+title_list[i].text)
    if cnt%2 !=0:
        rank.append(cnt)
        titleList.append(title_list[i].text)
        nameList.append(singer_list[i].text)
driver.quit()
data = {'순위': rank,
        '제목': titleList,
        '가수': nameList
        }
df = pd.DataFrame(data,columns=['순위','제목','가수'])

outlook = win32com.client.Dispatch("Outlook.Application")
newMail = outlook.CreateItem(0)
temp = df.to_html(index=False, justify='center')
#메일 to
newMail.To = "sunhee.na@amkor.co.kr"
#메일 cc걸기
#newMail.CC = "XXX.XXX@amkor.co.kr"
#메일 제목
newMail.Subject = "멜론 Top100 중 홀수 순위 입니다."
#메일 내용
newMail.HTMLBody = temp
newMail.Send()

====== WebDriver manager ======
Current google-chrome version is 102.0.5005
Get LATEST chromedriver version for 102.0.5005 google-chrome
Driver [C:\Users\suhna\.wdm\drivers\chromedriver\win32\102.0.5005.61\chromedriver.exe] found in cache
C:\Users\suhna\AppData\Local\Temp\4/ipykernel_10432/2903807663.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())
C:\Users\suhna\AppData\Local\Temp\4/ipykernel_10432/2903807663.py:9: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  title_list = driver.find_elements_by_xpath("//div[contains(@class,'ellipsis rank01')]")
C:\Users\suhna\AppData\Local\Temp\4/ipykernel_10432/2903807663.py:10: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  singer_list = driver.find_elements_by_xpath("//div[contains(@class,'ellipsis rank02')]")